"""Initial_Fix

Revision ID: 3c521a426ab3
Revises: 3768f5a2f8a8
Create Date: 2026-02-05 09:38:36.090754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c521a426ab3'
down_revision: Union[str, Sequence[str], None] = '3768f5a2f8a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytic_candles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_time', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('interval', sa.String(), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('high_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('low_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analytic_candles')
    # ### end Alembic commands ###
